import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [("core", "0001_initial"), ("evidence", "0001_initial"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="Questionnaire", fields=[("id", models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4, editable=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("name", models.CharField(max_length=240)), ("buyer_name", models.CharField(blank=True, max_length=180)), ("status", models.CharField(default="READY", max_length=20)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="questionnaires", to="core.organization")), ("owner", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Question", fields=[("id", models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4, editable=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("question_number", models.CharField(blank=True, max_length=40)), ("question_text", models.TextField()), ("required", models.BooleanField(default=True)), ("sort_order", models.PositiveIntegerField(default=0)), ("status", models.CharField(default="UNANSWERED", max_length=20)), ("questionnaire", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="questionnaires.questionnaire"))], options={"ordering": ["sort_order", "id"]}),
        migrations.CreateModel(name="AnswerDraft", fields=[("id", models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4, editable=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("version", models.PositiveIntegerField(default=1)), ("answer_text", models.TextField(blank=True)), ("generation_mode", models.CharField(default="AI", max_length=16)), ("status", models.CharField(default="NEEDS_REVIEW", max_length=20)), ("confidence", models.DecimalField(decimal_places=4, default=0, max_digits=5)), ("grounding_score", models.DecimalField(decimal_places=4, default=0, max_digits=5)), ("commitment_risk_score", models.DecimalField(decimal_places=4, default=0, max_digits=5)), ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="questionnaires.question"))]),
        migrations.CreateModel(name="AnswerCitation", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("quoted_excerpt", models.TextField(blank=True)), ("source_locator", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)), ("answer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="citations", to="questionnaires.answerdraft")), ("evidence", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="evidence.evidenceatom"))]),
        migrations.CreateModel(name="ApprovalEvent", fields=[("id", models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4, editable=False)), ("action", models.CharField(max_length=24)), ("previous_status", models.CharField(max_length=20)), ("new_status", models.CharField(max_length=20)), ("comment", models.TextField(blank=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)), ("answer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="approval_events", to="questionnaires.answerdraft")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.organization"))]),
        migrations.CreateModel(name="ExportJob", fields=[("id", models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4, editable=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("format", models.CharField(default="XLSX", max_length=8)), ("status", models.CharField(default="QUEUED", max_length=16)), ("file", models.FileField(blank=True, upload_to="exports/%Y/%m/")), ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.organization")), ("questionnaire", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="questionnaires.questionnaire"))]),
    ]
