import { useState } from 'react'
import { NavLink, Route, Routes, useLocation } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Activity, ArrowRight, Bell, BookOpenCheck, Check, ChevronDown, CircleHelp, Clock3, FileCheck2, FileText, FolderOpen, LayoutDashboard, LoaderCircle, Plus, Search, Settings2, ShieldCheck, UploadCloud, Users, X } from 'lucide-react'
import { api, type Document, type Evidence, type Questionnaire } from './api'

const nav = [
  {label:'Overview', to:'/', icon:LayoutDashboard},
  {label:'Questionnaires', to:'/questionnaires', icon:FileCheck2, count:'queue'},
  {label:'Evidence library', to:'/evidence', icon:BookOpenCheck},
  {label:'Source documents', to:'/documents', icon:FolderOpen},
]
const titleFor = (path:string) => nav.find(item => item.to === path)?.label ?? 'Overview'
function App() {
  const location = useLocation(); const [token,setToken] = useState(localStorage.getItem('proofgraph_access') ?? '')
  const orgs = useQuery({ queryKey:['organizations',token], queryFn:()=>api<{id:string;name:string;role:string}[]>('/api/organizations/'), enabled:!!token })
  const orgId = orgs.data?.[0]?.id
  if (orgId && localStorage.getItem('proofgraph_organization') !== orgId) localStorage.setItem('proofgraph_organization', orgId)
  const [notice,setNotice] = useState('')
  return <div className="app-shell">
    <aside className="sidebar">
      <a href="/" className="brand"><span className="brand-mark"><ShieldCheck size={20}/></span><span>proofgraph<small>Evidence workspace</small></span></a>
      <div className="workspace-switch"><div className="org-avatar">{orgs.data?.[0]?.name?.slice(0,1).toUpperCase() ?? 'P'}</div><span className="org-label">{orgs.data?.[0]?.name ?? 'Your workspace'}<small>{orgs.data?.[0]?.role ?? 'Sign in to continue'}</small></span><ChevronDown size={15}/></div>
      <span className="nav-caption">WORKSPACE</span><nav aria-label="Main navigation">{nav.map(item=><NavLink key={item.to} to={item.to} end={item.to==='/'} className={({isActive})=>`nav-link ${isActive?'active':''}`}><item.icon size={17}/><span>{item.label}</span>{item.count==='queue'&&<span className="nav-count">{orgId?'—':'0'}</span>}</NavLink>)}</nav>
      <span className="nav-caption tools-label">MANAGE</span><button className="nav-link quiet" onClick={()=>setNotice('Team member management is not enabled yet.')}><Users size={17}/>Team members</button><button className="nav-link quiet" onClick={()=>setNotice('Settings are being added to this workspace.')}><Settings2 size={17}/>Settings</button>
      <div className="sidebar-bottom"><div className="plan-card"><div className="plan-icon"><Activity size={16}/></div><strong>Your evidence, in one place</strong><p>Every answer can trace back to a source your team trusts.</p><a href="/evidence">Explore evidence <ArrowRight size={13}/></a></div><button className="nav-link quiet help-link" onClick={()=>setNotice('Help center is not connected yet.')}><CircleHelp size={17}/>Help center</button><div className="user-row"><div className="user-avatar">{token?'U':'?'}</div><span>{token?'Signed-in user':'Not signed in'}<small>{token?'Personal workspace':'Connect an account'}</small></span><button className="icon-button" aria-label="Notifications" onClick={()=>setNotice('No new notifications.')}><Bell size={16}/></button></div></div>
    </aside>
    <main className="main-area"><header className="topbar"><div className="breadcrumbs"><span>Workspace</span><span className="crumb-slash">/</span><strong>{titleFor(location.pathname)}</strong></div><div className="top-actions"><span className="secure-pill"><span/> Private workspace</span><button className="top-icon" aria-label="Search" onClick={()=>setNotice('Search is available in the evidence library.')}><Search size={17}/></button><div className="top-avatar">{token?'U':'?'}</div></div></header>
      <Routes><Route path="/" element={<Dashboard token={token} setToken={setToken} orgId={orgId} />} /><Route path="/evidence" element={<EvidencePage orgId={orgId}/>} /><Route path="/documents" element={<DocumentsPage orgId={orgId}/>} /><Route path="/questionnaires" element={<QuestionnairesPage orgId={orgId}/>} /></Routes>
    </main>{notice&&<div className="toast" role="status"><span>{notice}</span><button aria-label="Dismiss" onClick={()=>setNotice('')}><X size={15}/></button></div>}
  </div>
}

function PageHeader({eyebrow,title,subtitle,action}:{eyebrow:string;title:string;subtitle:string;action?:React.ReactNode}) { return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div>{action}</div> }
function Dashboard({token,setToken,orgId}:{token:string;setToken:(v:string)=>void;orgId?:string}) {
  const [showAuth,setShowAuth] = useState(!token)
  const {data:docs=[]} = useQuery({queryKey:['documents',orgId],queryFn:()=>api<Document[]>('/api/evidence/documents/'),enabled:!!orgId})
  const {data:evidenceData} = useQuery({queryKey:['evidence',orgId],queryFn:()=>api<{results?:Evidence[]}|Evidence[]>('/api/evidence/'),enabled:!!orgId})
  const evidence = Array.isArray(evidenceData)?evidenceData:evidenceData?.results??[]
  const {data:questionnaires=[]} = useQuery({queryKey:['questionnaires',orgId],queryFn:()=>api<{results?:Questionnaire[]}|Questionnaire[]>('/api/questionnaires/'),enabled:!!orgId})
  const qs = Array.isArray(questionnaires)?questionnaires:questionnaires.results??[]
  const ready = evidence.filter(e=>e.verification_status==='VERIFIED').length
  const today = new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'}).toUpperCase()
  return <div className="page-content"><PageHeader eyebrow={today} title="Good morning" subtitle="Here’s the latest on your company’s evidence and responses." action={<button className="button primary" onClick={()=>document.getElementById('file-upload')?.click()}><Plus size={16}/> Add source document</button>}/>
    {!token&&<div className="auth-strip"><div className="auth-symbol"><ShieldCheck size={19}/></div><div><strong>Connect your workspace</strong><p>Sign in to load your organization’s private evidence.</p></div><button className="button small-button" onClick={()=>setShowAuth(true)}>Sign in <ArrowRight size={14}/></button></div>}
    <section className="stats-grid" aria-label="Workspace summary"><Metric icon={<FolderOpen size={17}/>} label="Source documents" value={orgId?docs.length:'—'} foot={orgId?'In your library':'Connect workspace'} tone="violet"/><Metric icon={<BookOpenCheck size={17}/>} label="Verified evidence" value={orgId?ready:'—'} foot={orgId?`${evidence.length-ready} need review`:'Grounded in source docs'} tone="green"/><Metric icon={<FileCheck2 size={17}/>} label="Questionnaires" value={orgId?qs.length:'—'} foot={orgId?'Across your workspace':'Ready for your next RFP'} tone="blue"/><Metric icon={<Clock3 size={17}/>} label="Awaiting review" value="—" foot="Review queue connection pending" tone="amber"/></section>
    <section className="dashboard-grid"><div className="panel recent-panel"><div className="panel-heading"><div><h2>Recent source documents</h2><p>Documents are the starting point for trusted answers.</p></div><a href="/documents" className="text-link">View library <ArrowRight size={14}/></a></div>{docs.length? <div className="document-list">{docs.slice(0,5).map((doc)=><div className="document-row" key={doc.id}><div className="doc-icon"><FileText size={17}/></div><div className="doc-name"><strong>{doc.title}</strong><span>{doc.document_type} · Added {new Date(doc.created_at).toLocaleDateString()}</span></div><Status status={doc.status}/></div>)}</div>:<Empty icon={<FolderOpen size={21}/>} title="Your source library is ready" description="Add a trusted company document to start building a traceable evidence base." action={<UploadControl orgId={orgId}/>}/>}</div>
    <div className="panel progress-panel"><div className="panel-heading"><div><h2>Evidence health</h2><p>Verification keeps answers dependable.</p></div><span className="health-icon"><ShieldCheck size={16}/></span></div><div className="health-ring-wrap"><div className="health-ring"><div><strong>{evidence.length?Math.round(ready/evidence.length*100):0}%</strong><span>verified</span></div></div></div><div className="health-legend"><span><i className="dot green-dot"/>Verified <b>{ready}</b></span><span><i className="dot gray-dot"/>Needs review <b>{evidence.length-ready}</b></span></div><a href="/evidence" className="button secondary wide-button">Review evidence <ArrowRight size={14}/></a></div></section>
    <section className="lower-grid"><div className="panel questionnaire-panel"><div className="panel-heading"><div><h2>Questionnaire activity</h2><p>Keep customer requests moving with grounded answers.</p></div><a href="/questionnaires" className="text-link">See all <ArrowRight size={14}/></a></div>{qs.length?<div className="document-list">{qs.slice(0,4).map(q=><div className="document-row" key={q.id}><div className="doc-icon blue-doc"><FileCheck2 size={17}/></div><div className="doc-name"><strong>{q.name}</strong><span>{q.buyer_name||'Buyer not specified'} · {q.question_count} questions</span></div><Status status={q.status}/></div>)}</div>:<div className="inline-empty"><span className="inline-icon"><FileCheck2 size={18}/></span><span><strong>No questionnaires yet</strong><small>Upload an RFP or questionnaire to begin.</small></span><ArrowRight size={15}/></div>}</div><div className="tip-card"><div className="tip-top"><span className="tip-icon"><ShieldCheck size={17}/></span><span>PROOFGRAPH PRINCIPLE</span></div><blockquote>“I don’t have enough evidence” is better than an unsupported answer.</blockquote><p>ProofGraph keeps source, freshness, and verification status attached to every claim.</p><a href="/evidence">Explore your evidence <ArrowRight size={14}/></a></div></section>
    {showAuth&&<AuthDialog close={()=>setShowAuth(false)} success={v=>{localStorage.setItem('proofgraph_access',v);setToken(v);setShowAuth(false)}}/>}
  </div>
}
function Metric({icon,label,value,foot,tone}:{icon:React.ReactNode;label:string;value:string|number;foot:string;tone:string}){return <article className="metric-card"><div className={`metric-icon ${tone}`}>{icon}</div><span className="metric-label">{label}</span><strong className="metric-value">{value}</strong><span className="metric-foot">{foot}</span></article>}
function Status({status}:{status:string}) { const s=status.toLowerCase(); return <span className={`status status-${s}`}>{s==='ready'||s==='verified'?<Check size={12}/>:<span className="status-dot"/>}{status.replaceAll('_',' ').toLowerCase()}</span> }
function Empty({icon,title,description,action}:{icon:React.ReactNode;title:string;description:string;action?:React.ReactNode}){return <div className="empty-state"><span className="empty-icon">{icon}</span><strong>{title}</strong><p>{description}</p>{action}</div>}
function UploadControl({orgId}:{orgId?:string}) {
  const client=useQueryClient()
  const mutation=useMutation({mutationFn:(file:File)=>{const data=new FormData();data.append('file',file);data.append('title',file.name);return api<Document>('/api/evidence/documents/',{method:'POST',body:data})},onSuccess:()=>client.invalidateQueries({queryKey:['documents']})})
  return <label className="button secondary upload-label"><input id="file-upload" type="file" accept=".pdf,.docx,.xlsx,.csv,.txt,.md" disabled={!orgId||mutation.isPending} onChange={e=>e.target.files?.[0]&&mutation.mutate(e.target.files[0])}/>{mutation.isPending?<LoaderCircle className="spin" size={15}/>:<UploadCloud size={15}/>} {mutation.isPending?'Uploading…':orgId?'Upload a document':'Sign in to upload'}</label>
}
function EvidencePage({orgId}:{orgId?:string}) { const {data,error,isLoading}=useQuery({queryKey:['evidence',orgId],queryFn:()=>api<{results?:Evidence[]}|Evidence[]>('/api/evidence/'),enabled:!!orgId});const rows=Array.isArray(data)?data:data?.results??[];return <div className="page-content"><PageHeader eyebrow="KNOWLEDGE BASE" title="Evidence library" subtitle="Source-backed facts your team can safely reuse." action={<a className="button primary" href="/documents"><Plus size={16}/> Add source</a>}/>{error?<div className="error-box">Could not load evidence. Check your connection and try again.</div>:isLoading?<div className="skeleton-list" aria-label="Loading evidence"><i/><i/><i/></div>:rows.length?<div className="panel table-panel"><table><thead><tr><th>Evidence</th><th>Source</th><th>Type</th><th>Verification</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.title||row.content.slice(0,80)}</strong><small>{row.content.slice(0,120)}</small></td><td>{row.document_title}</td><td>{row.evidence_type.toLowerCase()}</td><td><Status status={row.verification_status}/></td></tr>)}</tbody></table></div>:<div className="panel"><Empty icon={<BookOpenCheck size={21}/>} title="No evidence to show" description={orgId?'Evidence is extracted from your uploaded sources and kept linked to the original.':'Sign in to see your organization’s evidence.'} action={<a className="button secondary" href="/documents">Browse source documents</a>}/></div>}</div> }
function DocumentsPage({orgId}:{orgId?:string}) {const {data=[],error,isLoading}=useQuery({queryKey:['documents',orgId],queryFn:()=>api<Document[]>('/api/evidence/documents/'),enabled:!!orgId});return <div className="page-content"><PageHeader eyebrow="SOURCE LIBRARY" title="Source documents" subtitle="Manage the trusted materials behind your company’s evidence." action={<UploadControl orgId={orgId}/>}/>{error?<div className="error-box">Could not load documents. Try again.</div>:isLoading?<div className="skeleton-list"><i/><i/></div>:data.length?<div className="panel table-panel"><table><thead><tr><th>Document</th><th>Type</th><th>Trust</th><th>Status</th></tr></thead><tbody>{data.map(doc=><tr key={doc.id}><td><strong>{doc.title}</strong><small>Added {new Date(doc.created_at).toLocaleDateString()}</small></td><td>{doc.document_type}</td><td>{doc.trust_level.toLowerCase()}</td><td><Status status={doc.status}/></td></tr>)}</tbody></table></div>:<div className="panel"><Empty icon={<UploadCloud size={21}/>} title="Start with a trusted source" description="Upload a policy, product guide, certification, or other company document." action={<UploadControl orgId={orgId}/>} /></div>}</div>}
function QuestionnairesPage({orgId}:{orgId?:string}) {const {data,error,isLoading}=useQuery({queryKey:['questionnaires',orgId],queryFn:()=>api<{results?:Questionnaire[]}|Questionnaire[]>('/api/questionnaires/'),enabled:!!orgId});const rows=Array.isArray(data)?data:data?.results??[];return <div className="page-content"><PageHeader eyebrow="CUSTOMER RESPONSES" title="Questionnaires" subtitle="Review incoming requests and keep each answer grounded in evidence." action={<button className="button primary" disabled title="Questionnaire ingestion is not enabled yet"><Plus size={16}/> New questionnaire</button>}/>{!orgId?<div className="panel"><Empty icon={<FileCheck2 size={20}/>} title="Connect your workspace" description="Sign in to view your organization’s questionnaires."/></div>:error?<div className="error-box">Could not load questionnaires. Try again.</div>:isLoading?<div className="skeleton-list"><i/><i/></div>:rows.length?<div className="panel table-panel"><table><thead><tr><th>Questionnaire</th><th>Buyer</th><th>Questions</th><th>Status</th></tr></thead><tbody>{rows.map(q=><tr key={q.id}><td><strong>{q.name}</strong></td><td>{q.buyer_name||'—'}</td><td>{q.question_count}</td><td><Status status={q.status}/></td></tr>)}</tbody></table></div>:<div className="panel"><Empty icon={<FileCheck2 size={21}/>} title="No questionnaires yet" description="Questionnaire file ingestion is being completed; this workspace will list requests as soon as they are available."/></div>}</div>}
function AuthDialog({close,success}:{close:()=>void;success:(token:string)=>void}){const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);try{const result=await api<{access:string}>('/api/auth/token/',{method:'POST',body:JSON.stringify({username:form.get('email'),password:form.get('password')})});success(result.access)}catch{setError('Sign-in failed. Check the API connection and your credentials.')}finally{setBusy(false)}}return <div className="modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="auth-modal" role="dialog" aria-modal="true" aria-labelledby="sign-in-title"><button className="modal-close" aria-label="Close sign in" onClick={close}><X size={17}/></button><span className="brand-mark modal-mark"><ShieldCheck size={20}/></span><h2 id="sign-in-title">Welcome back</h2><p>Sign in to your ProofGraph workspace.</p><form onSubmit={submit}><label>Email address<input name="email" type="email" autoComplete="username" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label>{error&&<span className="form-error" role="alert">{error}</span>}<button className="button primary modal-submit" disabled={busy}>{busy?<LoaderCircle size={16} className="spin"/>:'Sign in securely'}</button></form><small>New organizations can register through the API. Email verification and password reset delivery are not configured in this environment.</small></section></div>}

export default App
