import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("core", "0001_initial")]
    operations = [
        migrations.CreateModel(name="SourceDocument", fields=[("id", models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4, editable=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("title", models.CharField(max_length=240)), ("document_type", models.CharField(default="OTHER", max_length=40)), ("trust_level", models.CharField(default="UNVERIFIED", max_length=20)), ("status", models.CharField(default="UPLOADED", max_length=20)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="core.organization")), ("owner", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="DocumentVersion", fields=[("id", models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4, editable=False)), ("version_number", models.PositiveIntegerField()), ("file", models.FileField(upload_to="source-documents/%Y/%m/")), ("original_filename", models.CharField(max_length=255)), ("mime_type", models.CharField(max_length=120)), ("file_size", models.PositiveBigIntegerField()), ("sha256_hash", models.CharField(max_length=64)), ("processing_status", models.CharField(default="QUEUED", max_length=20)), ("created_at", models.DateTimeField(auto_now_add=True)), ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="evidence.sourcedocument"))]),
        migrations.AddConstraint(model_name="documentversion", constraint=models.UniqueConstraint(fields=("document", "version_number"), name="unique_document_version")),
        migrations.CreateModel(name="DocumentSection", fields=[("id", models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4, editable=False)), ("section_type", models.CharField(max_length=24)), ("section_path", models.TextField(blank=True)), ("page_number", models.PositiveIntegerField(blank=True, null=True)), ("sheet_name", models.CharField(blank=True, max_length=120)), ("content", models.TextField()), ("start_offset", models.PositiveIntegerField(blank=True, null=True)), ("end_offset", models.PositiveIntegerField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("version", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="evidence.documentversion"))]),
        migrations.CreateModel(name="EvidenceAtom", fields=[("id", models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4, editable=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("title", models.CharField(blank=True, max_length=240)), ("content", models.TextField()), ("evidence_type", models.CharField(default="OTHER", max_length=40)), ("source_locator", models.JSONField(blank=True, default=dict)), ("verification_status", models.CharField(choices=[("UNVERIFIED", "Unverified"), ("VERIFIED", "Verified"), ("STALE", "Stale"), ("REVOKED", "Revoked"), ("CONFLICTED", "Conflicted")], default="UNVERIFIED", max_length=16)), ("confidence", models.DecimalField(decimal_places=4, default=0, max_digits=5)), ("content_hash", models.CharField(blank=True, max_length=64)), ("verified_at", models.DateTimeField(blank=True, null=True)), ("document", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evidence", to="evidence.sourcedocument")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidence", to="core.organization")), ("verified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ("version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evidence", to="evidence.documentversion"))]),
        migrations.CreateModel(name="EvidenceClaim", fields=[("id", models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4, editable=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("subject", models.CharField(max_length=240)), ("predicate", models.CharField(max_length=120)), ("object_text", models.TextField(blank=True)), ("status", models.CharField(default="ACTIVE", max_length=16)), ("confidence", models.DecimalField(decimal_places=4, default=0, max_digits=5)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.organization"))]),
        migrations.CreateModel(name="ClaimEvidence", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("relationship_type", models.CharField(default="DIRECT", max_length=16)), ("claim", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="evidence.evidenceclaim")), ("evidence", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="evidence.evidenceatom"))]),
        migrations.AddConstraint(model_name="claimevidence", constraint=models.UniqueConstraint(fields=("claim", "evidence"), name="unique_claim_evidence")),
    ]
